### ISSUE TITLE
Add (config) option to disable FTOP, option to disable FCHAT

### ISSUE THREAD

**Issue by IAISI** [FactionsU/UID#35]
### Idea
Option to disable FTOP even if FTop plugin is not installed, FTOP should be enabled by default I guess

Option to disable all FChat features in case there's another plugin that handles this.

### Details
I think this could be done by moving registration of chat cmds into done() in FCmdRoot

```
        if (Bukkit.getServer().getPluginManager().isPluginEnabled("FactionsChat") || Bukkit.getServer().getPluginManager().isPluginEnabled("FactionsPlus")) {
            FactionsPlugin.getInstance().getLogger().info("Found FactionsChat/FactionsPlus plugin. Disabling our own /f chat commands.");
        } else {
            this.addSubCommand(this.cmdChat);
            this.addSubCommand(this.cmdToggleAllianceChat);
            this.addSubCommand(this.cmdChatSpy);
        }
```

but I'm not too familiar with FactionsUUID yet so I'm not sure if this could cause issues. Also I've implemented based on plugins, sorta like how (optional) FTOP works, but I think generic config option to just disable FChat for example, would be better approach.

**Comment by mbax** [comment]
Just don't grant the permission node (which is granted by default, mind you) for the top command, and there is a config option for disabling FUUID adding a tag to chat - `tagHandledByAnotherPlugin` - and for disabling /f chat stuff - `factionOnlyChat`
