### ISSUE TITLE
Option for Plugins to register new Permissions and new PermissibleActions

### ISSUE THREAD

**Issue by IAISI** [FactionsU/UID#36]
### Idea
When trying to extend or integrate Factions into other plugins, I think it would be very helpful if we could register (create) new Permissions and PermissibleActions.

### Details
I'm not sure if I missed something but so far I couldn't find a way to do this without building own Factions .jar

**Comment by mbax** [comment]
`PermSelectorRegistry` and `PermissibleActionRegistry`
