### ISSUE TITLE
Unclaimall not updating power

### ISSUE THREAD

**Issue by iLemon** [FactionsU/UID#41]
### Debug info
*Run `/f ticketinfo` and paste the URL here.*
https://ticket.factions.support/jitzJMFJilhpduEY7qpyqhIKlZZDALER

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://pastes.dev/hZXDRtkpfe (no error when unclaimall)

### Details
*Please explain the problem.*
If a player claims land, then does `/f unclaimall`, the factions land usage doesn't update.

https://www.youtube.com/watch?v=leoK5ekIY-4

**Comment by mbax** [comment]
Well, this is just wild! I'll look into this ASAP. Can you try restarting to see if it comes up correctly (and if there's mention of cleaning up bad claims during startup)?

**Comment by mbax** [comment]
Don't worry about the previous request - this should be resolved in 0.7.2
